kind: Pod
apiVersion: v1
metadata:
  generateName: mindcraft-bot-
spec:
  restartPolicy: Always
  serviceAccountName: default
  priority: 0
  containers:
    - resources: {}
      name: mindcraft
      ports: []
      imagePullPolicy: IfNotPresent
      image: image-registry.openshift-image-registry.svc:5000/virtual-ai-odyssey/mindcraft:latest
      env:
        - name: MINECRAFT_SERVER_HOST
          value: "minecraft-server"
        - name: MINECRAFT_SERVER_PORT
          value: "8080"
        - name: MODEL_SERVER_ENDPOINT
          value: "https://model-server"
        - name: MODEL 
          value: "gpt-4"
        - name: OPENAI_API_KEY
          value: key
        - name: PROFILE
          value: demojam
